//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perscabnewEntities : DbContext
    {
        public perscabnewEntities()
            : base("name=perscabnewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDocType> tblDocType { get; set; }
        public virtual DbSet<tblUserInfo> tblUserInfo { get; set; }
        public virtual DbSet<tblUserRole> tblUserRole { get; set; }
        public virtual DbSet<tblUserType> tblUserType { get; set; }
        public virtual DbSet<tblZayavkaChat> tblZayavkaChat { get; set; }
        public virtual DbSet<tblZayavkaDoc> tblZayavkaDoc { get; set; }
        public virtual DbSet<tblZayavkaType> tblZayavkaType { get; set; }
        public virtual DbSet<tblLog> tblLog { get; set; }
        public virtual DbSet<tblContract> tblContract { get; set; }
        public virtual DbSet<tblContractDoc> tblContractDoc { get; set; }
        public virtual DbSet<tblContractStatus> tblContractStatus { get; set; }
        public virtual DbSet<tblFilial> tblFilial { get; set; }
        public virtual DbSet<tblZayavkaStatus> tblZayavkaStatus { get; set; }
        public virtual DbSet<tblESignDoc> tblESignDoc { get; set; }
        public virtual DbSet<tblGP> tblGP { get; set; }
        public virtual DbSet<tblGP_Filial> tblGP_Filial { get; set; }
        public virtual DbSet<tblGP_Predstavitel> tblGP_Predstavitel { get; set; }
        public virtual DbSet<tblGP_PrichinaDE> tblGP_PrichinaDE { get; set; }
        public virtual DbSet<tbl1C_CenovayaKategoriya> tbl1C_CenovayaKategoriya { get; set; }
        public virtual DbSet<tbl1C_EnumUrovenU> tbl1C_EnumUrovenU { get; set; }
        public virtual DbSet<tbl1C_StatusOplaty> tbl1C_StatusOplaty { get; set; }
        public virtual DbSet<tbl1C_VidRassrochki> tbl1C_VidRassrochki { get; set; }
        public virtual DbSet<tbl1C_VidZayavki> tbl1C_VidZayavki { get; set; }
        public virtual DbSet<tblGP_DogovorEnergo> tblGP_DogovorEnergo { get; set; }
        public virtual DbSet<tblLogEventType> tblLogEventType { get; set; }
        public virtual DbSet<tblNotify> tblNotify { get; set; }
        public virtual DbSet<tblNotifyStatus> tblNotifyStatus { get; set; }
        public virtual DbSet<tblNotifyType> tblNotifyType { get; set; }
        public virtual DbSet<tblUserRegistrationType> tblUserRegistrationType { get; set; }
        public virtual DbSet<tblNotifyChannel> tblNotifyChannel { get; set; }
        public virtual DbSet<tblPrichinaPodachiZ> tblPrichinaPodachiZ { get; set; }
        public virtual DbSet<tblOrderSource> tblOrderSource { get; set; }
        public virtual DbSet<tblFIASRegionCity> tblFIASRegionCity { get; set; }
        public virtual DbSet<tblZayavka> tblZayavka { get; set; }
    }
}
