//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl1C_VidRassrochki
    {
        public byte[] C_IDRref { get; set; }
        public decimal C_EnumOrder { get; set; }
        public string caption_short { get; set; }
        public string caption_long { get; set; }
    }
}
