//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContract()
        {
            this.tblContractDoc = new HashSet<tblContractDoc>();
        }
    
        public System.Guid id_contract { get; set; }
        public Nullable<System.Guid> id_zayavka { get; set; }
        public string contract_number_1c { get; set; }
        public Nullable<System.DateTime> contract_date_1c { get; set; }
        public Nullable<int> id_contractstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContractDoc> tblContractDoc { get; set; }
        public virtual tblContractStatus tblContractStatus { get; set; }
        public virtual tblZayavka tblZayavka { get; set; }
    }
}
