//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractDoc
    {
        public System.Guid id_contractdoc { get; set; }
        public System.Guid id_contract { get; set; }
        public System.DateTime date_doc_add { get; set; }
        public string doc_file_name { get; set; }
        public string doc_file_path { get; set; }
        public int id_doctype { get; set; }
    
        public virtual tblContract tblContract { get; set; }
        public virtual tblDocType tblDocType { get; set; }
    }
}
