//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblESignDoc
    {
        public System.Guid id_esign { get; set; }
        public System.Guid id_zayavkadoc { get; set; }
        public Nullable<bool> verify_status { get; set; }
        public Nullable<System.Guid> verify_user { get; set; }
        public Nullable<System.DateTime> verify_datetime { get; set; }
        public System.Guid esign_docid { get; set; }
        public System.Guid esign_user { get; set; }
        public Nullable<System.DateTime> esign_date { get; set; }
    
        public virtual tblZayavkaDoc tblZayavkaDoc { get; set; }
        public virtual tblUserInfo tblUserInfo { get; set; }
    }
}
