//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGP_DogovorEnergo
    {
        public System.Guid id_dogovorenergo { get; set; }
        public Nullable<System.Guid> id_zayavka { get; set; }
        public Nullable<System.Guid> id_gp_predstavitel { get; set; }
        public Nullable<System.Guid> id_gp_filial { get; set; }
        public Nullable<System.Guid> id_gp { get; set; }
        public Nullable<System.Guid> id_prichinade { get; set; }
        public string nomer_ls { get; set; }
        public string nomer_dogovorenergo { get; set; }
        public string nomer_elektroustanovka { get; set; }
        public Nullable<System.DateTime> date_create_de { get; set; }
        public Nullable<System.DateTime> date_podpis_de { get; set; }
        public byte[] id_cenovayakategoriya { get; set; }
    
        public virtual tblGP_Predstavitel tblGP_Predstavitel { get; set; }
        public virtual tblGP_PrichinaDE tblGP_PrichinaDE { get; set; }
        public virtual tblZayavka tblZayavka { get; set; }
    }
}
