//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGP_Filial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGP_Filial()
        {
            this.tblGP_Predstavitel = new HashSet<tblGP_Predstavitel>();
        }
    
        public System.Guid id_gp_filial { get; set; }
        public System.Guid id_gp { get; set; }
        public string caption_GP_filial { get; set; }
    
        public virtual tblGP tblGP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGP_Predstavitel> tblGP_Predstavitel { get; set; }
    }
}
