//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGP_Predstavitel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGP_Predstavitel()
        {
            this.tblGP_DogovorEnergo = new HashSet<tblGP_DogovorEnergo>();
        }
    
        public System.Guid id_gp_predstavitel { get; set; }
        public string name_predstavitel { get; set; }
        public System.Guid id_gp_filial { get; set; }
        public System.Guid id_gp { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
    
        public virtual tblGP_Filial tblGP_Filial { get; set; }
        public virtual tblUserInfo tblUserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGP_DogovorEnergo> tblGP_DogovorEnergo { get; set; }
    }
}
