//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public Nullable<System.Guid> id_zayavka { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public string comment_log { get; set; }
        public System.Guid id_logrec { get; set; }
        public System.DateTime logrec_datetime { get; set; }
        public int id_logeventtype { get; set; }
    
        public virtual tblUserInfo tblUserInfo { get; set; }
        public virtual tblLogEventType tblLogEventType { get; set; }
        public virtual tblZayavka tblZayavka { get; set; }
    }
}
