//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotify
    {
        public System.Guid id_notify { get; set; }
        public System.Guid id_notifytype { get; set; }
        public System.DateTime date_create_notify { get; set; }
        public Nullable<System.Guid> recipient_id { get; set; }
        public Nullable<System.Guid> notifystatus_id { get; set; }
        public string notify_text { get; set; }
        public int priority { get; set; }
        public Nullable<System.DateTime> date_send_notify { get; set; }
        public Nullable<System.Guid> id_notifychannel { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> date_plan_notify { get; set; }
        public Nullable<System.Guid> link_id { get; set; }
        public string comment { get; set; }
    
        public virtual tblNotifyType tblNotifyType { get; set; }
        public virtual tblNotifyStatus tblNotifyStatus { get; set; }
        public virtual tblNotifyChannel tblNotifyChannel { get; set; }
    }
}
