//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZayavkaChat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblZayavkaChat()
        {
            this.tblZayavkaDoc = new HashSet<tblZayavkaDoc>();
        }
    
        public System.Guid id_zayavka { get; set; }
        public System.Guid id_chatrec { get; set; }
        public string caption_msg { get; set; }
        public System.Guid id_user { get; set; }
        public System.DateTime chatrec_datetime { get; set; }
        public Nullable<bool> istemp { get; set; }
        public Nullable<bool> isread { get; set; }
        public Nullable<System.Guid> isread_user { get; set; }
        public Nullable<System.DateTime> isread_datetime { get; set; }
    
        public virtual tblUserInfo tblUserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZayavkaDoc> tblZayavkaDoc { get; set; }
        public virtual tblZayavka tblZayavka { get; set; }
    }
}
