//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZayavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblZayavka()
        {
            this.tblContract = new HashSet<tblContract>();
            this.tblGP_DogovorEnergo = new HashSet<tblGP_DogovorEnergo>();
            this.tblLog = new HashSet<tblLog>();
            this.tblZayavkaDoc = new HashSet<tblZayavkaDoc>();
            this.tblZayavkaChat = new HashSet<tblZayavkaChat>();
        }
    
        public System.Guid id_user { get; set; }
        public System.Guid id_zayavka { get; set; }
        public int id_zayavkatype { get; set; }
        public string comment { get; set; }
        public System.DateTime date_create_zayavka { get; set; }
        public string zayavka_number_1c { get; set; }
        public Nullable<System.DateTime> zayavka_date_1c { get; set; }
        public bool is_viewed { get; set; }
        public Nullable<System.Guid> viewed_operator { get; set; }
        public Nullable<int> id_filial { get; set; }
        public Nullable<bool> is_temp { get; set; }
        public Nullable<int> id_zayavkastatus { get; set; }
        public byte[] id1C_EnumUrovenU { get; set; }
        public byte[] id1C_VidZayavki { get; set; }
        public byte[] id1C_CenovayaKategoriya { get; set; }
        public byte[] id1C_StatusOplaty { get; set; }
        public byte[] id1C_VidRassrochki { get; set; }
        public string v1C_adresEPU { get; set; }
        public Nullable<decimal> v1C_maxMoschnostEPU { get; set; }
        public Nullable<System.Guid> id_gp { get; set; }
        public byte[] v1C_StatusZayavki { get; set; }
        public string v1C_NomerDogovora { get; set; }
        public Nullable<System.DateTime> v1C_DataDogovora { get; set; }
        public byte[] v1C_StatusDogovora { get; set; }
        public string v1C_EPU { get; set; }
        public byte[] v1C_StatusOplaty { get; set; }
        public Nullable<bool> status_PrikreplenAktTP { get; set; }
        public Nullable<bool> status_PrikreplenAktDopuskaPU { get; set; }
        public Nullable<System.Guid> id_prichinapodachiz { get; set; }
        public string v1C_Zayavitel { get; set; }
        public Nullable<bool> status_GP_RegNewZ { get; set; }
        public Nullable<bool> status_GP_RegNewDTP { get; set; }
        public Nullable<bool> status_ZAnnulirovana { get; set; }
        public Nullable<bool> is_vremennaya { get; set; }
        public Nullable<System.Guid> id_ordersource { get; set; }
        public Nullable<System.DateTime> date_copy_from1c { get; set; }
        public Nullable<System.Guid> id_FIASRegionCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContract> tblContract { get; set; }
        public virtual tblFIASRegionCity tblFIASRegionCity { get; set; }
        public virtual tblFilial tblFilial { get; set; }
        public virtual tblGP tblGP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGP_DogovorEnergo> tblGP_DogovorEnergo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLog> tblLog { get; set; }
        public virtual tblOrderSource tblOrderSource { get; set; }
        public virtual tblPrichinaPodachiZ tblPrichinaPodachiZ { get; set; }
        public virtual tblUserInfo tblUserInfo { get; set; }
        public virtual tblZayavkaStatus tblZayavkaStatus { get; set; }
        public virtual tblZayavkaType tblZayavkaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZayavkaDoc> tblZayavkaDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZayavkaChat> tblZayavkaChat { get; set; }
    }
}
