//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZayavkaDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblZayavkaDoc()
        {
            this.tblESignDoc = new HashSet<tblESignDoc>();
        }
    
        public System.Guid id_zayavka { get; set; }
        public int id_doctype { get; set; }
        public System.Guid id_zayavkadoc { get; set; }
        public System.DateTime date_doc_add { get; set; }
        public string doc_file_name { get; set; }
        public string doc_file_path { get; set; }
        public Nullable<System.Guid> id_chatrec { get; set; }
        public Nullable<bool> is_temp { get; set; }
        public Nullable<System.Guid> id_contract { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public Nullable<System.Guid> esign_oke { get; set; }
        public Nullable<System.Guid> esign_kontr { get; set; }
    
        public virtual tblDocType tblDocType { get; set; }
        public virtual tblZayavkaChat tblZayavkaChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblESignDoc> tblESignDoc { get; set; }
        public virtual tblUserInfo tblUserInfo { get; set; }
        public virtual tblZayavka tblZayavka { get; set; }
    }
}
